"""add follow_up_at to draft_tickets

Revision ID: 40bd1ebcda20
Revises: ca081fe1f74d
Create Date: 2026-06-01 09:16:35.044280

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '40bd1ebcda20'
down_revision: Union[str, None] = 'ca081fe1f74d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_tickets', sa.Column('follow_up_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_tickets', 'follow_up_at')
    # ### end Alembic commands ###
