"""add departments table and forwarded draft status

Revision ID: ca4c445f94a2
Revises: 40bd1ebcda20
Create Date: 2026-06-01 09:30:59.446439

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ca4c445f94a2'
down_revision: Union[str, None] = '40bd1ebcda20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE draftstatus ADD VALUE IF NOT EXISTS 'forwarded'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reply_template', sa.Text(), nullable=True),
    sa.Column('sla_working_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.add_column('draft_tickets', sa.Column('forwarded_to_department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'draft_tickets', 'departments', ['forwarded_to_department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft_tickets', type_='foreignkey')
    op.drop_column('draft_tickets', 'forwarded_to_department_id')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
