"""add matched_contact_id and context_summary to draft_tickets

Revision ID: ca081fe1f74d
Revises: f43013171b86
Create Date: 2026-06-01 08:57:53.455191

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ca081fe1f74d'
down_revision: Union[str, None] = 'f43013171b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('source', sa.String(length=20), nullable=False))
    op.add_column('chat_sessions', sa.Column('whatsapp_phone', sa.String(length=50), nullable=True))
    op.add_column('draft_tickets', sa.Column('matched_contact_id', sa.UUID(), nullable=True))
    op.add_column('draft_tickets', sa.Column('context_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'draft_tickets', 'contacts', ['matched_contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'draft_tickets', type_='foreignkey')
    op.drop_column('draft_tickets', 'context_summary')
    op.drop_column('draft_tickets', 'matched_contact_id')
    op.drop_column('chat_sessions', 'whatsapp_phone')
    op.drop_column('chat_sessions', 'source')
    # ### end Alembic commands ###
