"""add context fields to draft_tickets

Revision ID: f43013171b86
Revises: bfadac4990f3
Create Date: 2026-06-01 08:25:47.291685

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f43013171b86'
down_revision: Union[str, None] = 'bfadac4990f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
